### ISSUE TITLE
using email

### ISSUE THREAD

**Issue by m0t0k0-2501** [devinsolutions/docker-osticket#11]
Hey, I am trying to get outgoing email to work with this image via the environment variables, and have been having issues.
I've used:
SMTP_HOST
SMTP_PORT
SMTP_FROM
SMTP_USER
SMTP_PASSWORD

and I'm sure all this information is correct, but once I log into the admin control panel and go to email settings, I don't see my email there, and when I go to diagnostics and try to send a test mail it doesn't work. Do you mind helping me get this working?

**Comment by lubo** [comment]
Hi @m0t0k0-2501, these settings are used by `msmtp`, that's why you don't see them in osTicket. See [`root/usr/local/src/osticket/setup/install.php`](https://github.com/devinsolutions/docker-osticket/blob/master/root/usr/local/src/osticket/setup/install.php). If this doesn't help, then you should probably ask in [CampbellSoftwareSolutions/docker-osticket](https://github.com/CampbellSoftwareSolutions/docker-osticket) as we don't use these settings.
