### ISSUE TITLE
Can HTTPS Support be added

### ISSUE THREAD

**Issue by RavenfireIT** [devinsolutions/docker-osticket#19]
Have everything set up and running great so far (thanks).

Would like to configure for HTTPS but it doesn't appear that it is enabled in the image.

Can it be configured or can you add it to the image?

Thanks in advance.

**Comment by adam-dej** [comment]
To keep this image as universal as possible, I believe it would be best to handle TLS termination outside of it. This allows users to handle it in a way that best fits their environment.

Therefore, please consider deploying a reverse proxy container that would do TLS termination for you. There are many options, like a simple nginx container, Traefik, etc.

If you want to handle TLS termination in the osTicket container, I suppose you can create your own `/etc/nginx/nginx.conf` based on the one in the image. You can then bind-mount it (along with the certificate and key) into the container. But I wouldn't recommend it since this file may change in the image. It would be up to you to keep track of these changes and update your copy.
