### ISSUE TITLE
Migration and rollback

### ISSUE THREAD

**Issue by tarikly** [devinsolutions/docker-osticket#30]
Any way so I can migrate a full populated setup running container from osticket [1.12.3] to the latest version of that image and rollback in case of failures ?

_Update: typo_

**Comment by bobweston** [comment]
I'm not working on this repo. (But I think it is great). But if it were me, I'd start migrating by following the upgrade paths on OSTicket github repo. I don't think it wise to try upgrading from 1.12.3 directly to 1.16.x.

If it were my install, I'd start by upgrading my existing install to the latest version of 1.12.x.

Then I'd do the next upgrade on that path.

I'd suggest taking database snapshots before each upgrade.

This may take longer. But it is the safest way to go.

**Comment by lubo** [comment]
Hi. We don't provide osTicket or infrastructure support here. I recommend you reviewing the change history of this image since the version you're upgrading from for any breaking changes and developing your upgrade strategy accordingly. I'm closing this as it looks like you haven't found any issue with this image.
