### ISSUE TITLE
Upgrade to 1.17.2 (or latest) not prompting for upgrade in OSTicket

### ISSUE THREAD

**Issue by liquidate** [devinsolutions/docker-osticket#39]
I've followed the upgrade instructions, but when I update my docker container to 1.17.2 and then log in with my offline account, I'm not prompted to update on the System Information page.  It tells me that I'm still running v1.16.3 (e148727) and that v1.16.5 is available (on osticket's website).  I'm using the repository:

devinsolutions/osticket:1.17.2 (or devinsolutions/osticket:latest)

Interestingly, my ldap logins aren't working when running this version, just the offline admin account I've created.  When I change back to devinsolutions/osticket:1.16.3 all of my login accounts work as expected.  Am I missing something?

**Comment by adam-dej** [comment]
Unfortunately, I'm not able to reproduce this issue with the given info. The "osTicket Upgrader" should be the first thing you see after you log in with a local admin account after switching the image version to 1.17.2 (and if you try to log in with a non-admin account, the login should fail with a "System Offline" message).

> Interestingly, my ldap logins aren't working when running this version

That is expected due to plugin-related changes in 1.17.x images, which would suggest that you are running an image that contains these changes, but somehow also has the old osTicket version.

- If you run `cat /var/www/html/bootstrap.php` in the running container, there should be definitions of `GIT_VERSION`, `MAJOR_VERSION`, and `THIS_VERSION`. To which values are these constants defined?
- Are you bind-mounting anything to `/var/www/html`? Are you overriding the image entry point in any way? Are you doing anything that could cause `/var/www/html` to contain an older osTicket installation?
- What happens if you navigate to `/scp/upgrade.php`?
- What is the image digest you are running?
- Can you list the plugins you have installed/enabled, so that I may try to reproduce this with a configuration that is closer to yours?

**Comment by liquidate** [comment]
I believe this ended up being user error.  I gave it another try, and I'm successfully using your release along with OSTicketAwesome without any issues.
